sudo: required
dist: trusty
language: java
addons:
  apt:
    packages:
    - graphviz
    - r-base
    - r-cran-rserve
    - r-cran-rjava
before_install:
- sudo rm -f /usr/lib/R/bin/Rserve
- sudo ln -s /usr/lib/R/site-library/Rserve/libs/Rserve /usr/lib/R/bin/Rserve
after_sucess:
  - bash <(curl -s https://codecov.io/bash)
